server:
  port: 8001


dubbo:
  application:
    name: dubbo-provider-server8001    #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
  registry:
    address: localhost:2181    # zookeeper地址

    protocol: zookeeper  #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
    check: false
  protocol:
    name: dubbo
    port: "20881"
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000



